version: '3'

tasks:
  docker-run:
    desc: Run the backend using Docker Compose
    cmds:
      - docker-compose up --build

  docker-stop:
    desc: Stop the running Docker Compose services
    cmds:
      - docker-compose down

  docker-logs:
    desc: View logs of the running services
    cmds:
      - docker-compose logs -f

  docker-shell:
    desc: Open a shell in the running app container
    cmds:
      - docker-compose exec app /bin/sh

  run:
    desc: Run the backend using uvicorn
    cmds:
      - poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000